version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=imagestore
    ports:
      - '5432:5432'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27006:27006"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@localhost:5432/imagestore?sslmode=disable
    depends_on:
      - postgres
    command: [ "/app/main" ]