apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}-dbcredentials
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.db.username | default "" | b64enc }}
  DB_PASSWORD: {{ .Values.db.password | default "" | b64enc }}
